//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAssignment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstAssignment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01e61cc37113f90b388559d5198634ec {
            get {
                object obj = ResourceManager.GetObject("01e61cc37113f90b388559d5198634ec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _201904071554648068625 {
            get {
                object obj = ResourceManager.GetObject("201904071554648068625", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50_Beautiful_and_Minimalist_Presentation_Backgrounds_025 {
            get {
                object obj = ResourceManager.GetObject("50-Beautiful-and-Minimalist-Presentation-Backgrounds-025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50_Beautiful_and_Minimalist_Presentation_Backgrounds_0251 {
            get {
                object obj = ResourceManager.GetObject("50-Beautiful-and-Minimalist-Presentation-Backgrounds-0251", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50_Beautiful_and_Minimalist_Presentation_Backgrounds_0252 {
            get {
                object obj = ResourceManager.GetObject("50-Beautiful-and-Minimalist-Presentation-Backgrounds-0252", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _712vK5vqZgL__SY606_ {
            get {
                object obj = ResourceManager.GetObject("712vK5vqZgL._SY606_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _712vK5vqZgL1 {
            get {
                object obj = ResourceManager.GetObject("712vK5vqZgL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _99wo {
            get {
                object obj = ResourceManager.GetObject("99wo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _99wo1 {
            get {
                object obj = ResourceManager.GetObject("99wo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a8ffcc241e1d80079cd7b0a93de72e38 {
            get {
                object obj = ResourceManager.GetObject("a8ffcc241e1d80079cd7b0a93de72e38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Abstract_Red_Circles_PPT_Templates_680x510 {
            get {
                object obj = ResourceManager.GetObject("Abstract-Red-Circles-PPT-Templates-680x510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_ {
            get {
                object obj = ResourceManager.GetObject("download (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_1 {
            get {
                object obj = ResourceManager.GetObject("download (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_2 {
            get {
                object obj = ResourceManager.GetObject("download (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_3 {
            get {
                object obj = ResourceManager.GetObject("download (2)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dT87rzETe {
            get {
                object obj = ResourceManager.GetObject("dT87rzETe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap faded_red_watercolor_background_23_2147836044 {
            get {
                object obj = ResourceManager.GetObject("faded-red-watercolor-background_23-2147836044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap faded_red_watercolor_background_23_21478360441 {
            get {
                object obj = ResourceManager.GetObject("faded-red-watercolor-background_23-21478360441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flash_ {
            get {
                object obj = ResourceManager.GetObject("flash_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gallery_hero_il_fullxfull_1138965407_r9ln {
            get {
                object obj = ResourceManager.GetObject("gallery_hero_il_fullxfull.1138965407_r9ln", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy_2_ {
            get {
                object obj = ResourceManager.GetObject("giphy(2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy_2_1 {
            get {
                object obj = ResourceManager.GetObject("giphy(2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy_2_2 {
            get {
                object obj = ResourceManager.GetObject("giphy(2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy_2_3 {
            get {
                object obj = ResourceManager.GetObject("giphy(2)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy_2_4 {
            get {
                object obj = ResourceManager.GetObject("giphy(2)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy_2_5 {
            get {
                object obj = ResourceManager.GetObject("giphy(2)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoldenSnitch_PM {
            get {
                object obj = ResourceManager.GetObject("GoldenSnitch_PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoldenSnitch_PM1 {
            get {
                object obj = ResourceManager.GetObject("GoldenSnitch_PM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap googlelogo_color_120x44dp {
            get {
                object obj = ResourceManager.GetObject("googlelogo_color_120x44dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gryffindor_crest_drawing_18_best_pin_by_neta_shribman_on_harry_potter_pinterest_of_gryffindor_crest_drawing {
            get {
                object obj = ResourceManager.GetObject("gryffindor-crest-drawing-18-best-pin-by-neta-shribman-on-harry-potter-pinterest-o" +
                        "f-gryffindor-crest-drawing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Harry_Potter_Hogwarts_logo {
            get {
                object obj = ResourceManager.GetObject("Harry-Potter-Hogwarts-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Harry_Potter_Hogwarts_logo1 {
            get {
                object obj = ResourceManager.GetObject("Harry-Potter-Hogwarts-logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hogwarts_castle_monn_print {
            get {
                object obj = ResourceManager.GetObject("hogwarts-castle-monn-print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hogwarts_castle_monn_print1 {
            get {
                object obj = ResourceManager.GetObject("hogwarts-castle-monn-print1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hptvthogjt_1_1200x1200 {
            get {
                object obj = ResourceManager.GetObject("hptvthogjt_1_1200x1200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hptvthogjt_1_1200x12001 {
            get {
                object obj = ResourceManager.GetObject("hptvthogjt_1_1200x12001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hu {
            get {
                object obj = ResourceManager.GetObject("hu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_harry_potter_and_the_deathly_hallows_hogwarts_scho_hogwarts_logo_png_clipart_background_png_mart_5c0343a79233c0_9419738815437177995989_1_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-harry-potter-and-the-deathly-hallows-hogwarts-scho-hogwarts-logo-png-clip" +
                        "art-background-png-mart-5c0343a79233c0.9419738815437177995989(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap large_7_ {
            get {
                object obj = ResourceManager.GetObject("large(7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap large_7_1 {
            get {
                object obj = ResourceManager.GetObject("large(7)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maxresdefault_2_ {
            get {
                object obj = ResourceManager.GetObject("maxresdefault(2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oRX3Zbe {
            get {
                object obj = ResourceManager.GetObject("oRX3Zbe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_01_08_09_01_17 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_01-08-09.01.17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_01_08_09_10_10 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_01-08-09.10.10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_01_08_09_11_16 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_01-08-09.11.16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_01_08_09_15_57 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_01-08-09.15.57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_07_11_47 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-07.11.47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_07_21_46 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-07.21.46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_07_211 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-07.211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_07_212 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-07.212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_08_27_28 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-08.27.28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_08_27_50 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-08.27.50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_08_28_13 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-08.28.13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_05_08_28_39 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-05-08.28.39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_29_19 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.29.19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_33_53 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.33.53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_331 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.331", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_34_14 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.34.14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_34_29 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.34.29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_34_44 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.34.44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_341 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.341", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_342 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.342", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_343 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.343", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_04_07_08_344 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_04-07-08.344", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_11_10_22_16 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-11-10.22.16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_11_10_22_31 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-11-10.22.31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_11_10_24_20 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-11-10.24.20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_11_10_241 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-11-10.241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_31_08 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.31.08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_31_50 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.31.50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_311 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_312 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.312", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_313 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.313", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_314 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.314", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_315 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.315", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_45_03 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.45.03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_451 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.451", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_452 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.452", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_453 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.453", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_454 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.454", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_03_455 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-03.455", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_04_37_12 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-04.37.12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_08_12_04 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-08.12.04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_09_53_03 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-09.53.03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_09_531 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-09.531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_09_55_12 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-09.55.12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_12_09_551 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-12-09.551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_13_07_31_32 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-13-07.31.32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_13_07_32_22 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-13-07.32.22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_13_07_32_51 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-13-07.32.51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_13_07_33_24 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-13-07.33.24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_13_07_33_39 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-13-07.33.39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_13_07_33_57 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-13-07.33.57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_13_07_54_45 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-13-07.54.45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_08_52_57 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-08.52.57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_08_521 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-08.521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_08_522 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-08.522", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_08_523 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-08.523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_08_524 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-08.524", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_08_53_54 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-08.53.54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_09_12_50 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-09.12.50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_09_17_39 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-09.17.39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_10_09_03 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-10.09.03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_10_09_25 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-10.09.25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_10_091 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-10.091", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_10_092 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-10.092", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_14_10_093 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-14-10.093", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_15_04_04_50 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-15-04.04.50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_15_07_45_46 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-15-07.45.46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_15_07_451 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-15-07.451", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_15_07_52_24 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-15-07.52.24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_15_08_12_53 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-15-08.12.53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_15_08_34_26 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-15-08.34.26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_29_07_06_09 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-29-07.06.09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_29_07_061 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-29-07.061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_29_08_26_52 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-29-08.26.52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_29_08_27_55 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-29-08.27.55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicsArt_12_29_08_271 {
            get {
                object obj = ResourceManager.GetObject("PicsArt_12-29-08.271", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rainbow_colors_3_t2 {
            get {
                object obj = ResourceManager.GetObject("rainbow_colors_3-t2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_and_white_watercolor_background_design_1034_740 {
            get {
                object obj = ResourceManager.GetObject("red-and-white-watercolor-background-design_1034-740", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_and_white_watercolor_background_design_1034_7401 {
            get {
                object obj = ResourceManager.GetObject("red-and-white-watercolor-background-design_1034-7401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_and_white_watercolor_background_design_1034_7402 {
            get {
                object obj = ResourceManager.GetObject("red-and-white-watercolor-background-design_1034-7402", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_and_white_watercolor_background_design_1034_7403 {
            get {
                object obj = ResourceManager.GetObject("red-and-white-watercolor-background-design_1034-7403", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RjSCmf6 {
            get {
                object obj = ResourceManager.GetObject("RjSCmf6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RjSCmf61 {
            get {
                object obj = ResourceManager.GetObject("RjSCmf61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RjSCmf62 {
            get {
                object obj = ResourceManager.GetObject("RjSCmf62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RjSCmf63 {
            get {
                object obj = ResourceManager.GetObject("RjSCmf63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap solid_red_fabric_Robert_Kaufman_USA_Red_179485_1 {
            get {
                object obj = ResourceManager.GetObject("solid-red-fabric-Robert-Kaufman-USA-Red-179485-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap solid_red_fabric_Robert_Kaufman_USA_Red_179485_11 {
            get {
                object obj = ResourceManager.GetObject("solid-red-fabric-Robert-Kaufman-USA-Red-179485-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap solid_red_fabric_Robert_Kaufman_USA_Red_179485_12 {
            get {
                object obj = ResourceManager.GetObject("solid-red-fabric-Robert-Kaufman-USA-Red-179485-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap solid_red_fabric_Robert_Kaufman_USA_Red_179485_13 {
            get {
                object obj = ResourceManager.GetObject("solid-red-fabric-Robert-Kaufman-USA-Red-179485-13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap solid_red_fabric_Robert_Kaufman_USA_Red_179485_14 {
            get {
                object obj = ResourceManager.GetObject("solid-red-fabric-Robert-Kaufman-USA-Red-179485-14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap solid_red_fabric_Robert_Kaufman_USA_Red_179485_15 {
            get {
                object obj = ResourceManager.GetObject("solid-red-fabric-Robert-Kaufman-USA-Red-179485-15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sonic {
            get {
                object obj = ResourceManager.GetObject("sonic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sonic1 {
            get {
                object obj = ResourceManager.GetObject("sonic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sonic2 {
            get {
                object obj = ResourceManager.GetObject("sonic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sonic21 {
            get {
                object obj = ResourceManager.GetObject("sonic21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spider_sorting_hat {
            get {
                object obj = ResourceManager.GetObject("spider-sorting-hat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tenor {
            get {
                object obj = ResourceManager.GetObject("tenor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tenor1 {
            get {
                object obj = ResourceManager.GetObject("tenor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpapers_For_Galaxy_S4_Colorful_60 {
            get {
                object obj = ResourceManager.GetObject("Wallpapers-For-Galaxy-S4-Colorful-60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watercolour_texture_background_1048_6656 {
            get {
                object obj = ResourceManager.GetObject("watercolour-texture-background_1048-6656", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
